### ISSUE TITLE
[feature]: Kernal timer need to add a interface to support temporary timer use.

### ISSUE THREAD

**Issue by At-EC** [At-EC/At-RTOS#10]
Kernal timer need to support temporary timer for the short time or once timer use.

**Comment by Intellectual777** [comment]
> Kernal timer need to support temporary timer for the short time or once timer use.

**Comment by Intellectual777** [comment]
``

**Comment by At-EC** [comment]
> > Kernal timer need to support temporary timer for the short time or once timer use.

        os_timer_id_t id = os_timer_init(NULL, OS_TIMER_CTRL_TEMPORARY, 1000, "TempTimer");
        do {
            loop++; 
        } while(os_timer_busy(id));
        
    
    The enhanced timer feature that can allocate a temporary timer and automatically free it by itself for a short use. pls check the lastest commit. 

    Thanks,
    Riven
